In [1]:
import numpy as np
arr = np.arange(1, 21)
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_median = np.median(arr)
arr_std = np.std(arr)
indices_gt_10 = np.where(arr > 10)[0]
print("Array:", arr)
print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Median:", arr_median)
print("Standard Deviation:", arr_std)
print("Indices of elements > 10:", indices_gt_10)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr_2d = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:")
print(arr_2d)
transpose_arr = arr_2d.T
print("\nTranspose of the array:")
print(transpose_arr)
row_sums = np.sum(arr_2d, axis=1)
print("\nRow-wise sums:")
print(row_sums)
col_sums = np.sum(arr_2d, axis=0)
print("\nColumn-wise sums:")
print(col_sums)


Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sums:
[10 26 42 58]

Column-wise sums:
[28 32 36 40]


In [ ]:
import numpy as np
np.random.seed(0)
A = np.random.randint(1, 21, size=(3, 3))
B = np.random.randint(1, 21, size=(3, 3))
addition = A + B
subtraction = A - B
multiplication = A * B
dot_product = np.dot(A, B)
print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nDot Product of A and B:")
print(dot_product)


Array A:
[[13 16  1]
 [ 4  4  8]
 [10 20 19]]

Array B:
[[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]

Element-wise Addition:
[[18 23 14]
 [ 6 11 16]
 [25 38 25]]

Element-wise Subtraction:
[[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]

Element-wise Multiplication:
[[ 65 112  13]
 [  8  28  64]
 [150 360 114]]

Dot Product of A and B:
[[112 221 303]
 [148 200 132]
 [375 552 404]]


In [ ]:
import numpy as np
arr = np.arange(1, 13)
arr_2d = arr.reshape(3, 4)
sliced = arr_2d[:2, -2:]
print("Original 2D array (3x4):")
print(arr_2d)
print("\nSliced array (first two rows, last two columns):")
print(sliced)


Original 2D array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced array (first two rows, last two columns):
[[3 4]
 [7 8]]
